// frontend.old/src/components/LightDarkSwitch.svelte
<script lang="ts">
import { onMount } from "svelte";
import { DARK_MODE, LIGHT_MODE } from "@constants/constants";
import Icon from "@iconify/svelte";
import { getStoredTheme, setTheme, type ThemeSwitchOrigin } from "@utils/setting-utils";
import type { LIGHT_DARK_MODE } from "@/types/config";

let mode: LIGHT_DARK_MODE = $state(getStoredTheme());
let isChanging = false;

function syncModeFromStorage() {
	mode = getStoredTheme();
}

function originFromButton(el: HTMLElement): ThemeSwitchOrigin {
	const r = el.getBoundingClientRect();
	return { x: r.left + r.width / 2, y: r.top + r.height / 2 };
}

async function switchScheme(newMode: LIGHT_DARK_MODE, origin?: ThemeSwitchOrigin) {
	if (isChanging || newMode === mode) return;
	isChanging = true;
	mode = newMode;
	try {
		await setTheme(newMode, origin);
	} finally {
		isChanging = false;
	}
}

function onToggle(e: MouseEvent) {
	const el = e.currentTarget as HTMLElement | null;
	const next = mode === LIGHT_MODE ? DARK_MODE : LIGHT_MODE;
	switchScheme(next, el ? originFromButton(el) : undefined);
}

onMount(() => {
	syncModeFromStorage();
	document.addEventListener("astro:page-load", syncModeFromStorage);
	return () => {
		document.removeEventListener("astro:page-load", syncModeFromStorage);
	};
});
</script>

<button
	type="button"
	aria-label={mode === DARK_MODE ? "切换到浅色模式" : "切换到深色模式"}
	class="btn-plain scale-animation relative z-[60] h-11 w-11 rounded-lg active:scale-90"
	id="scheme-switch"
	data-mode={mode}
	onclick={onToggle}
>
	<div
		class="icon-layer absolute inset-0 flex items-center justify-center transition-all duration-300 ease-in-out"
		class:opacity-0={mode !== LIGHT_MODE}
		class:scale-75={mode !== LIGHT_MODE}
		class:rotate-90={mode !== LIGHT_MODE}
		aria-hidden={mode !== LIGHT_MODE}
	>
		<Icon icon="material-symbols:wb-sunny-outline-rounded" class="text-[1.25rem]" />
	</div>
	<div
		class="icon-layer absolute inset-0 flex items-center justify-center transition-all duration-300 ease-in-out"
		class:opacity-0={mode !== DARK_MODE}
		class:scale-75={mode !== DARK_MODE}
		class:-rotate-90={mode !== DARK_MODE}
		aria-hidden={mode !== DARK_MODE}
	>
		<Icon icon="material-symbols:dark-mode-outline-rounded" class="text-[1.25rem]" />
	</div>
</button>

<style>
	.icon-layer {
		pointer-events: none;
	}
</style>

// frontend/app/components/LightDarkSwitch.vue
<script setup lang="ts">
const auth = useAuth()
const settingsApi = useSettingsApi()
const { theme, toggleLightDark, loadLocal, snapshot } = useAppearancePreferences()

const isDark = ref(false)
const changing = ref(false)

function syncFromDocument() {
  if (!import.meta.client) return
  isDark.value = document.documentElement.classList.contains('dark')
}

async function persistPreference() {
  if (!auth.isAuthenticated.value) return
  await settingsApi.savePreferences(snapshot()).catch(() => {})
}

async function onToggle(event: MouseEvent) {
  if (changing.value) return
  changing.value = true
  try {
    await toggleLightDark(event)
    syncFromDocument()
    await persistPreference()
  } finally {
    changing.value = false
  }
}

onMounted(() => {
  auth.hydrate()
  loadLocal()
  syncFromDocument()
})

watch(theme, () => nextTick(syncFromDocument))
</script>

<template>
  <button
    type="button"
    class="scheme-switch"
    aria-label="明暗切换"
    :data-mode="isDark ? 'dark' : 'light'"
    :disabled="changing"
    @click="onToggle"
  >
    <span class="icon-layer" :class="{ inactive: isDark }" aria-hidden="true">
      <UIcon name="i-lucide-sun" class="size-5" />
    </span>
    <span class="icon-layer" :class="{ inactive: !isDark }" aria-hidden="true">
      <UIcon name="i-lucide-moon" class="size-5" />
    </span>
  </button>
</template>

<style scoped>
.scheme-switch {
  position: relative;
  z-index: 60;
  display: grid;
  width: 2.5rem;
  height: 2.5rem;
  place-items: center;
  border-radius: 0.65rem;
  color: var(--ui-text-muted);
  transition: background-color 160ms ease, color 160ms ease, transform 160ms ease;
}

.scheme-switch:hover {
  background: var(--ui-bg-elevated);
  color: var(--ui-text);
}

.scheme-switch:active {
  transform: scale(0.94);
}

.scheme-switch:disabled {
  cursor: wait;
  opacity: 0.72;
}

.icon-layer {
  position: absolute;
  inset: 0;
  display: grid;
  place-items: center;
  pointer-events: none;
  transition: opacity 260ms ease, transform 260ms ease;
}

.icon-layer.inactive {
  opacity: 0;
  transform: scale(0.72) rotate(90deg);
}

.scheme-switch[data-mode="dark"] .icon-layer.inactive {
  transform: scale(0.72) rotate(-90deg);
}
</style>
